### ISSUE TITLE
Do we need this?

### ISSUE THREAD

**Issue by artalat** [BlueBaseJS/plugin-console-logger_old#3]
Do we?

**Comment by abubakarmani1** [comment]
we have another plugin which is under development, we can delete this one once [plugin-console-logger](https://github.com/BlueBaseJS/plugin-console-logger) will published

**Comment by artalat** [comment]
@hassans-be @danial24 when can we make this happen?

cc: @ammarkhan967

**Comment by artalat** [comment]
reopening it, till we delete this repo
